langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
  - yes | gem update --system --force
  - gem install bundler
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: MwNECR/qjl/fhIrcsHpYsD1jyv17HMhKXoq7jGC1aLoKV898y4aS5mrmbvTFQ10pxRf6+v2NSgNArCt0TVAjIyQH4kwxoUrBd9dZACphHkMgfT27CEDXQUluCpRxT5bBClgBpXTKdgjHqdnTZ2ilOJjp0vLr+Urg/MAvTtIeLlVwGWD748+hGD4TXIl/pRyTFmn6M9js4I6aG1qxe7brkrV3u0diIpOqKWXZhM9MyVvvat8ziYs0PbV4rNUVsich6j2SqQJwEiNYZH+HpaJg0+gjkKpL8vrWIgYjCU5+JX58mOO7Ek6YRqs/2WyaDG9IRwRwcxN9lCq2FSKYWMwHLtCqbsFKGbMmhcubVZzgRbzdRldfJ2FTZKt3xFMxOT/EdriC/of2Gh87H5MSx/LyudMq24OEYz4TXAR1wsPRhcZLYsCkFN+v17dKeXNwi6VyWhBcZHEv2nmkaV8FcDksdK0irXpOM/y/WSuTJD96TPURhB/Q3iR5wtwLZBA4CVnfhiNb3a0yuMloZs+lnjTregWtibNvMv7lezorJgVw7mxWXMa9eVzO1Ji1aJ0lEVOIFUOrADHOoU5LRC7hJdkJzaUBdpPXUttfvqu9I3E43Mf8nm2PSEEsOJFToCM9GcfuGdYFWXbKoxQoDbtU8lAomH7W7hEtIWb5rWDxeAkd6jU=
  app: brownfield-paired-tt-eh
  run: rails db:migrate
